/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 11/10/2011, 06:27:16 PM
 */
package interfaz;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.logica;

/**
 *
 * @author Sandra Milena Guevara Morales
 */
public class Interfaz extends javax.swing.JFrame {

    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        opciones = new javax.swing.JComboBox();
        lienzo = new javax.swing.JPanel();
        graficar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CÓDIGOS DE LINEA");

        jLabel2.setText("Ingrese señal (max 18 bits)");

        jLabel3.setText("Elija un codigo");

        opciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UP-NRZ", "UP-RZ", "P-NRZ-L", "P-NRZ-I", "P-RZ", "MANCHESTER", "MANCHESTER DIF.", "AMI", "HDB3", "DB8Z" }));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        lienzo.setBackground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        graficar.setText("Graficar");
        graficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graficarMouseClicked(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graficar)
                        .addGap(18, 18, 18)
                        .addComponent(borrar)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graficar)
                    .addComponent(borrar))
                .addGap(18, 18, 18)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
    }//GEN-LAST:event_opcionesActionPerformed

    private void graficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficarMouseClicked
        logica.reloj(codigo.getText(), lienzo.getGraphics());
        logica.dibujarLineasVerticales(codigo.getText(), lienzo.getGraphics());
        logica.dibujarNiveles(lienzo.getGraphics());
        logica.dibujarLineaHorizontal(lienzo.getGraphics());
        logica.señal(codigo.getText(), lienzo.getGraphics());
        if(opciones.getSelectedItem().equals("UP-NRZ")){
            logica.up_nrz(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("UP-RZ")){
            logica.up_rz(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("P-NRZ-L")){
            logica.p_nrz_l(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("P-NRZ-I")){
            logica.p_nrz_i(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("P-RZ")){
            logica.p_rz(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("MANCHESTER")){
            logica.manchester(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("MANCHESTER DIF.")){
            logica.manchester_Diferencial(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("AMI")){
            logica.ami(codigo.getText(),lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("HDB3")){
            logica.hdb3(codigo.getText(), lienzo.getGraphics());
        }
        else if(opciones.getSelectedItem().equals("DB8Z")){
            logica.db8z(codigo.getText(), lienzo.getGraphics());
        }
    }//GEN-LAST:event_graficarMouseClicked

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        lienzo.setBackground(Color.red);
        lienzo.setBackground(Color.black);
    }//GEN-LAST:event_borrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton graficar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel lienzo;
    private javax.swing.JComboBox opciones;
    // End of variables declaration//GEN-END:variables
}
